organization:
    id: 7841a19a-0f62-449d-99fd-9ac2e7cf43a2
    name: Cloudview
project:
    id: 9bed8555-e05e-40ab-a048-46d1f57d6f4e
    slug: circleci/FrHdEECdfVkLV2JSSViNhP/LFmaenAhmJP5UrmUWG34Wq
    name: reglet
