import type { MasterRule } from './master.js';
import type { ProviderId } from './providers/types.js';

export const LEGACY_GENERATED_HEADER = `<!-- ⚠️ GENERATED BY REGLET — DO NOT EDIT THIS FILE DIRECTLY.
Source of truth: ~/.reglet/rules/  (edit those files, then \`reglet apply\`, or let the daemon do it)
Agents: if you need to change these instructions or add new ones, edit the files in
~/.reglet/rules/ instead of this file. To stop reglet from managing this file, run:
  reglet unenroll <provider>:rules
Hand-edits here will be detected as drift and you'll be prompted to import or discard them. -->`;

export const GENERATED_HEADER = `<!-- ⚠️ GENERATED BY REGLET — DO NOT EDIT THIS FILE DIRECTLY.
Source of truth: ~/.reglet/rules/  (edit those files, then use Review & Apply)
Agents: if you need to change these instructions or add new ones, edit the files in
~/.reglet/rules/ instead of this file. To stop reglet from managing this file, run:
  reglet unenroll <provider>:rules
Hand-edits here will be reported as drift and will not be overwritten automatically. -->`;

export function renderRulesFile(provider: ProviderId, ruleFiles: MasterRule[]): string {
  const header = GENERATED_HEADER.replace('<provider>', provider);
  const body = ruleFiles
    .filter((rule) => rule.targets === undefined || rule.targets.includes(provider))
    .map((rule) => `<!-- source: rules/${rule.relPath} -->\n\n${rule.content.trimEnd()}`)
    .join('\n\n---\n\n');

  return body.length === 0 ? `${header}\n` : `${header}\n\n${body}\n`;
}
