import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { afterEach, describe, expect, test } from 'bun:test';

const execFileAsync = promisify(execFile);
const cliPath = path.resolve(import.meta.dir, '..', 'src', 'index.ts');

let currentHome: string | undefined;
let currentProviderHome: string | undefined;

afterEach(async () => {
  if (currentHome !== undefined) {
    await rm(currentHome, { recursive: true, force: true });
    currentHome = undefined;
  }
  if (currentProviderHome !== undefined) {
    await rm(currentProviderHome, { recursive: true, force: true });
    currentProviderHome = undefined;
  }
});

async function useTempHomes(): Promise<{ home: string; providerHome: string }> {
  currentHome = await mkdtemp(path.join(tmpdir(), 'reglet-cli-home-'));
  currentProviderHome = await mkdtemp(path.join(tmpdir(), 'reglet-cli-provider-'));
  return { home: currentHome, providerHome: currentProviderHome };
}

async function runCli(args: string[], home: string, providerHome: string): Promise<{ stdout: string; stderr: string }> {
  const result = await execFileAsync('bun', [cliPath, ...args], {
    env: {
      ...process.env,
      REGLET_HOME: home,
      REGLET_PROVIDER_HOME: providerHome,
    },
  });
  return { stdout: result.stdout, stderr: result.stderr };
}

describe('reglet CLI', () => {
  test('init --yes enrolls detected providers, imports rules, and applies outputs', async () => {
    const { home, providerHome } = await useTempHomes();
    const claudeRules = path.join(providerHome, '.claude', 'CLAUDE.md');
    await mkdir(path.dirname(claudeRules), { recursive: true });
    await writeFile(claudeRules, 'existing claude rules\n');
    await mkdir(path.join(providerHome, '.claude', 'skills', 'alpha'), { recursive: true });
    await writeFile(path.join(providerHome, '.claude', 'skills', 'alpha', 'SKILL.md'), 'alpha skill\n');
    await writeFile(
      path.join(providerHome, '.claude.json'),
      `${JSON.stringify(
        {
          theme: 'dark',
          mcpServers: {
            existingServer: {
              command: 'node',
              args: ['server.js'],
              env: { TOKEN: 'one' },
            },
          },
        },
        null,
        2,
      )}\n`,
    );

    await runCli(['init', '--yes'], home, providerHome);

    expect(await readFile(path.join(home, 'rules', 'imported-claude.md'), 'utf8')).toBe('existing claude rules\n');
    expect(await readFile(path.join(home, 'skills', 'alpha', 'SKILL.md'), 'utf8')).toBe('alpha skill\n');
    expect(JSON.parse(await readFile(path.join(home, 'mcp', 'servers.json'), 'utf8'))).toEqual({
      mcpServers: {
        existingServer: {
          command: 'node',
          args: ['server.js'],
          env: { TOKEN: 'one' },
        },
      },
    });
    expect(await readFile(claudeRules, 'utf8')).toContain('GENERATED BY REGLET');
    expect(JSON.parse(await readFile(path.join(providerHome, '.claude.json'), 'utf8'))).toEqual({
      theme: 'dark',
      mcpServers: {
        existingServer: {
          command: 'node',
          args: ['server.js'],
          env: { TOKEN: 'one' },
        },
      },
    });
    expect(await readFile(path.join(home, 'reglet.toml'), 'utf8')).toContain('[providers.claude]');
    expect(await readFile(path.join(home, 'reglet.toml'), 'utf8')).toContain('enabled = true');
  });

  test('init --yes imports opencode mcp schema into canonical master format', async () => {
    const { home, providerHome } = await useTempHomes();
    const opencodeConfig = path.join(providerHome, '.config', 'opencode', 'opencode.json');
    await mkdir(path.dirname(opencodeConfig), { recursive: true });
    await writeFile(
      opencodeConfig,
      `${JSON.stringify(
        {
          mcp: {
            localServer: {
              type: 'local',
              command: ['node', 'server.js'],
              environment: { TOKEN: 'one' },
            },
            remoteServer: {
              type: 'remote',
              url: 'https://example.test/mcp',
            },
          },
        },
        null,
        2,
      )}\n`,
    );

    await runCli(['init', '--yes'], home, providerHome);

    expect(JSON.parse(await readFile(path.join(home, 'mcp', 'servers.json'), 'utf8'))).toEqual({
      mcpServers: {
        localServer: {
          command: 'node',
          args: ['server.js'],
          env: { TOKEN: 'one' },
        },
        remoteServer: {
          url: 'https://example.test/mcp',
        },
      },
    });
  });

  test('init with provider and content flags imports only selected content', async () => {
    const { home, providerHome } = await useTempHomes();
    const claudeRules = path.join(providerHome, '.claude', 'CLAUDE.md');
    await mkdir(path.join(providerHome, '.claude', 'skills', 'alpha'), { recursive: true });
    await writeFile(claudeRules, 'selected rules\n');
    await writeFile(path.join(providerHome, '.claude', 'skills', 'alpha', 'SKILL.md'), 'should not import\n');
    await writeFile(
      path.join(providerHome, '.claude.json'),
      `${JSON.stringify({ mcpServers: { shouldNotImport: { command: 'node' } } }, null, 2)}\n`,
    );

    await runCli(['init', '--provider', 'claude', '--content', 'rules'], home, providerHome);

    expect(await readFile(path.join(home, 'rules', 'imported-claude.md'), 'utf8')).toBe('selected rules\n');
    await expect(readFile(path.join(home, 'skills', 'alpha', 'SKILL.md'), 'utf8')).rejects.toThrow();
    expect(JSON.parse(await readFile(path.join(home, 'mcp', 'servers.json'), 'utf8'))).toEqual({ mcpServers: {} });
    const config = await readFile(path.join(home, 'reglet.toml'), 'utf8');
    expect(config).toContain('[providers.claude]');
    expect(config).toContain('enabled = true');
    expect(config).toContain('rules = true');
    expect(config).toContain('skills = false');
    expect(config).toContain('mcp = false');
  });

  test('apply, status --check, and restore work in a sandbox', async () => {
    const { home, providerHome } = await useTempHomes();
    const claudeDir = path.join(providerHome, '.claude');
    await mkdir(path.join(home, 'rules'), { recursive: true });
    await mkdir(claudeDir, { recursive: true });
    await writeFile(path.join(home, 'rules', '00-general.md'), 'Be concise.\n');
    await writeFile(
      path.join(home, 'reglet.toml'),
      [
        '[providers.claude]',
        'enabled = true',
        'rules = true',
        'skills = true',
        'mcp = true',
        '',
        '[sync]',
        'server_url = ""',
        '',
      ].join('\n'),
    );

    const apply = await runCli(['apply', '--provider', 'claude', '--content', 'rules'], home, providerHome);
    expect(apply.stdout).toContain('claude\trules\twritten');

    const outputPath = path.join(claudeDir, 'CLAUDE.md');
    await writeFile(outputPath, `${await readFile(outputPath, 'utf8')}\nhand edit\n`);
    await expect(runCli(['status', '--check'], home, providerHome)).rejects.toMatchObject({ code: 2 });

    const restore = await runCli(['restore', 'claude'], home, providerHome);
    expect(restore.stdout).toContain('claude\tremoved');
    await expect(readFile(outputPath, 'utf8')).rejects.toThrow();
  });

  test('import provider rules writes stripped drift back into master rules', async () => {
    const { home, providerHome } = await useTempHomes();
    const claudeDir = path.join(providerHome, '.claude');
    await mkdir(path.join(home, 'rules'), { recursive: true });
    await mkdir(claudeDir, { recursive: true });
    await writeFile(path.join(home, 'rules', '00-general.md'), 'Base rules.\n');
    await writeFile(
      path.join(home, 'reglet.toml'),
      [
        '[providers.claude]',
        'enabled = true',
        'rules = true',
        'skills = true',
        'mcp = true',
        '',
        '[sync]',
        'server_url = ""',
        '',
      ].join('\n'),
    );
    await runCli(['apply', '--provider', 'claude', '--content', 'rules'], home, providerHome);

    const outputPath = path.join(claudeDir, 'CLAUDE.md');
    await writeFile(outputPath, `${await readFile(outputPath, 'utf8')}\nProvider-only edit.\n`);
    const result = await runCli(['import', 'claude:rules'], home, providerHome);

    expect(result.stdout).toContain('claude\trules\timported');
    const importedFile = result.stdout.trim().split('\t').at(-1);
    expect(importedFile).toBeDefined();
    expect(await readFile(importedFile ?? '', 'utf8')).not.toContain('GENERATED BY REGLET');
    expect(await readFile(importedFile ?? '', 'utf8')).toContain('Provider-only edit.');
  });

  test('enroll and unenroll update provider config', async () => {
    const { home, providerHome } = await useTempHomes();

    await runCli(['init'], home, providerHome);
    await runCli(['enroll', 'codex'], home, providerHome);
    await runCli(['unenroll', 'codex:mcp'], home, providerHome);
    const config = await readFile(path.join(home, 'reglet.toml'), 'utf8');

    expect(config).toContain('[providers.codex]');
    expect(config).toContain('enabled = true');
    expect(config).toContain('mcp = false');
  });

  test('login --token writes sync state with device name', async () => {
    const { home, providerHome } = await useTempHomes();

    await runCli(['login', 'http://reglet.test', '--token', 'dev-token', '--device', 'laptop'], home, providerHome);
    const state = JSON.parse(await readFile(path.join(home, '.state', 'sync.json'), 'utf8')) as unknown;

    expect(state).toMatchObject({
      version: 1,
      serverUrl: 'http://reglet.test',
      deviceToken: 'dev-token',
      deviceName: 'laptop',
    });
  });
});
